Repository astroML/astroML-notebooks, pull requests merged in 2022-09, with the labels that each got.

#57 Adding latex dependencies for binder apt install config
  .binder/apt.txt
Labels: infrastructure

#41 Extend readme
  chapter1/README.md
  chapter2/README.md
  chapter4/README.md
  index.md
Labels: documentation

#61 3.1 branch
  chapter3/README.md
  chapter3/astroml_chapter3_Overview_of_Probability_and_Random_Variables.ipynb
Labels: content

#67 Book with 4.1, 4.2, and 4.3
  chapter4/README.md
  chapter4/astroml_chapter4_Maximum_Likelihood_Estimation_and_Goodness_of_fit.ipynb
Labels: content

#65 4.4 branch
  chapter4/README.md
  chapter4/astroml_chapter4_Gaussian_mixtures.ipynb
Labels: content

#69 DOC: Updating HTML title and name
  conf.py
Labels: infrastructure
